import type { ENTOntologyEntry } from './types'

export const ENT_PROCEDURES_SEED: ENTOntologyEntry[] = [
  // ── OTOLOGIA ─────────────────────────────────────────────────────────────
  {
    id: 'timpanoplastia-tipo-1',
    name: 'Timpanoplastia Tipo I (Miringoplastia)',
    nameEN: 'Tympanoplasty Type I / Myringoplasty',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602011', display: 'Timpanoplastia tipo I' },
      { system: 'CID-10', code: 'H72', display: 'Perfuração da membrana do tímpano' },
    ],
    meshTerms: ['Tympanoplasty', 'Myringoplasty', 'Tympanic Membrane Perforation'],
    guidelines: [{ title: 'Clinical Practice Guideline: Tympanostomy Tubes in Children', organization: 'AAO-HNS', year: 2022, url: 'https://www.entnet.org/resource/tympanostomy-tubes-in-children-update/' }],
    commonDiagnoses: ['H72', 'H66'],
    avgDurationMinutes: 90,
    complexity: 2,
  },
  {
    id: 'timpanoplastia-tipo-2',
    name: 'Timpanoplastia Tipo II (com ossiculoplastia parcial)',
    nameEN: 'Tympanoplasty Type II',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602011', display: 'Timpanoplastia' },
      { system: 'CID-10', code: 'H74', display: 'Outras afecções do ouvido médio e mastoide' },
    ],
    meshTerms: ['Tympanoplasty', 'Ossiculoplasty', 'Ossicular Chain'],
    commonDiagnoses: ['H74', 'H72'],
    avgDurationMinutes: 120,
    complexity: 3,
  },
  {
    id: 'estapedotomia',
    name: 'Estapedotomia / Estapedectomia',
    nameEN: 'Stapedotomy / Stapedectomy',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602038', display: 'Estapedotomia' },
      { system: 'CID-10', code: 'H80', display: 'Otosclerose' },
    ],
    meshTerms: ['Stapedectomy', 'Stapedotomy', 'Otosclerosis', 'Stapes Surgery', 'Conductive Hearing Loss'],
    guidelines: [{ title: 'Otosclerosis Clinical Practice Guideline', organization: 'AAO-HNS', year: 2020, url: 'https://www.entnet.org' }],
    commonDiagnoses: ['H80'],
    avgDurationMinutes: 75,
    complexity: 4,
  },
  {
    id: 'mastoidectomia-radical-modificada',
    name: 'Mastoidectomia Radical Modificada',
    nameEN: 'Modified Radical Mastoidectomy',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602089', display: 'Mastoidectomia radical modificada' },
      { system: 'CID-10', code: 'H71', display: 'Colesteatoma do ouvido médio' },
    ],
    meshTerms: ['Mastoidectomy', 'Cholesteatoma', 'Middle Ear', 'Canal Wall Down'],
    commonDiagnoses: ['H71', 'H70'],
    avgDurationMinutes: 150,
    complexity: 4,
  },
  {
    id: 'mastoidectomia-conservadora',
    name: 'Mastoidectomia Conservadora (CWU)',
    nameEN: 'Canal Wall Up Mastoidectomy',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602070', display: 'Mastoidectomia simples' },
      { system: 'CID-10', code: 'H71', display: 'Colesteatoma do ouvido médio' },
    ],
    meshTerms: ['Mastoidectomy', 'Cholesteatoma', 'Canal Wall Up', 'Atticotomy'],
    commonDiagnoses: ['H71', 'H70'],
    avgDurationMinutes: 120,
    complexity: 3,
  },
  {
    id: 'implante-coclear',
    name: 'Implante Coclear',
    nameEN: 'Cochlear Implantation',
    subspecialty: 'neurotology',
    codes: [
      { system: 'TUSS', code: '30602119', display: 'Implante coclear — cirurgia' },
      { system: 'CID-10', code: 'H90', display: 'Perda de audição neuro-sensorial' },
    ],
    meshTerms: ['Cochlear Implants', 'Cochlear Implantation', 'Sensorineural Hearing Loss', 'Deafness'],
    guidelines: [{ title: 'Cochlear Implants in Adults and Children', organization: 'AAO-HNS', year: 2023, url: 'https://www.entnet.org/resource/cochlear-implants-in-adults-and-children/' }],
    commonDiagnoses: ['H90', 'H91'],
    avgDurationMinutes: 120,
    complexity: 5,
  },
  {
    id: 'tvt-miringotomia',
    name: 'Miringotomia com Tubo de Ventilação (TVT)',
    nameEN: 'Tympanostomy Tube Insertion',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30602046', display: 'Miringotomia com tubo de ventilação' },
      { system: 'CID-10', code: 'H65', display: 'Otite média não supurativa' },
    ],
    meshTerms: ['Middle Ear Ventilation', 'Tympanostomy', 'Otitis Media with Effusion', 'Grommets'],
    guidelines: [{ title: 'Tympanostomy Tubes in Children — Update', organization: 'AAO-HNS', year: 2022, url: 'https://www.entnet.org/resource/tympanostomy-tubes-in-children-update/' }],
    commonDiagnoses: ['H65.0', 'H65.2', 'H65.3'],
    avgDurationMinutes: 15,
    complexity: 1,
  },

  // ── RINOLOGIA ────────────────────────────────────────────────────────────
  {
    id: 'septoplastia',
    name: 'Septoplastia',
    nameEN: 'Septoplasty',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401018', display: 'Septoplastia' },
      { system: 'CID-10', code: 'J34.2', display: 'Desvio do septo nasal' },
    ],
    meshTerms: ['Septoplasty', 'Nasal Septum Deviation', 'Nasal Obstruction', 'Turbinate'],
    commonDiagnoses: ['J34.2'],
    avgDurationMinutes: 60,
    complexity: 2,
  },
  {
    id: 'fess',
    name: 'Cirurgia Endoscópica Sinusal Funcional (FESS)',
    nameEN: 'Functional Endoscopic Sinus Surgery (FESS)',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401050', display: 'Cirurgia endoscópica do seio paranasal' },
      { system: 'CID-10', code: 'J32', display: 'Sinusite crônica' },
    ],
    meshTerms: ['Endoscopy', 'Sinusitis', 'Paranasal Sinuses', 'Functional Endoscopic Sinus Surgery', 'Rhinosinusitis'],
    guidelines: [
      { title: 'EPOS 2020 — European Position Paper on Rhinosinusitis', organization: 'EPOS', year: 2020, url: 'https://www.rhinologyjournal.com/EPOS2020' },
      { title: 'Adult Sinusitis Clinical Practice Guideline', organization: 'AAO-HNS', year: 2023, url: 'https://www.entnet.org/resource/adult-sinusitis/' },
    ],
    commonDiagnoses: ['J32', 'J33'],
    avgDurationMinutes: 90,
    complexity: 3,
  },
  {
    id: 'turbinoplastia',
    name: 'Turbinoplastia / Turbinectomia Inferior',
    nameEN: 'Inferior Turbinate Reduction / Turbinoplasty',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401034', display: 'Turbinectomia' },
      { system: 'CID-10', code: 'J34.3', display: 'Hipertrofia dos cornetos nasais' },
    ],
    meshTerms: ['Turbinectomy', 'Nasal Turbinates', 'Inferior Turbinate Reduction', 'Nasal Obstruction'],
    commonDiagnoses: ['J34.3', 'J30'],
    avgDurationMinutes: 30,
    complexity: 1,
  },
  {
    id: 'polipectomia-nasal',
    name: 'Polipectomia Nasal Endoscópica',
    nameEN: 'Endoscopic Nasal Polypectomy',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401069', display: 'Polipectomia nasal' },
      { system: 'CID-10', code: 'J33', display: 'Pólipo nasal' },
    ],
    meshTerms: ['Nasal Polyps', 'Polypectomy', 'Chronic Rhinosinusitis', 'Eosinophilic'],
    guidelines: [
      { title: 'EPOS 2020', organization: 'EPOS', year: 2020, url: 'https://www.rhinologyjournal.com/EPOS2020' },
    ],
    commonDiagnoses: ['J33', 'J32'],
    avgDurationMinutes: 60,
    complexity: 2,
  },
  {
    id: 'cirurgia-base-cranio-anterior',
    name: 'Cirurgia Endoscópica de Base de Crânio Anterior',
    nameEN: 'Endoscopic Skull Base Surgery',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401115', display: 'Cirurgia endoscópica de base de crânio' },
      { system: 'CID-10', code: 'C30', display: 'Neoplasia maligna da cavidade nasal' },
    ],
    meshTerms: ['Skull Base Surgery', 'Endoscopy', 'Anterior Cranial Fossa', 'Pituitary Neoplasms'],
    commonDiagnoses: ['C30', 'D35.2', 'J34.8'],
    avgDurationMinutes: 240,
    complexity: 5,
  },

  // ── LARINGOLOGIA ─────────────────────────────────────────────────────────
  {
    id: 'microcirurgia-laringe',
    name: 'Microcirurgia de Laringe',
    nameEN: 'Laryngeal Microsurgery',
    subspecialty: 'laryngology',
    codes: [
      { system: 'TUSS', code: '30504034', display: 'Microcirurgia de laringe' },
      { system: 'CID-10', code: 'J38.1', display: 'Pólipo de corda vocal e laringe' },
    ],
    meshTerms: ['Laryngoscopy', 'Vocal Cord', 'Laryngeal Diseases', 'Phonosurgery', 'Microlaryngoscopy'],
    guidelines: [{ title: 'Hoarseness (Dysphonia) Guideline', organization: 'AAO-HNS', year: 2018, url: 'https://www.entnet.org/resource/hoarseness-dysphonia/' }],
    commonDiagnoses: ['J38.0', 'J38.1', 'J38.2'],
    avgDurationMinutes: 60,
    complexity: 3,
  },
  {
    id: 'traqueostomia',
    name: 'Traqueostomia',
    nameEN: 'Tracheostomy',
    subspecialty: 'laryngology',
    codes: [
      { system: 'TUSS', code: '30504050', display: 'Traqueostomia' },
      { system: 'CID-10', code: 'J95.0', display: 'Mau funcionamento de traqueostomia' },
    ],
    meshTerms: ['Tracheostomy', 'Airway Management', 'Trachea', 'Tracheotomy'],
    commonDiagnoses: ['J04', 'J38.6', 'Q31', 'J96'],
    avgDurationMinutes: 45,
    complexity: 3,
  },
  {
    id: 'laringoplastia-injecao',
    name: 'Laringoplastia por Injeção (Medialização)',
    nameEN: 'Injection Laryngoplasty',
    subspecialty: 'laryngology',
    codes: [
      { system: 'TUSS', code: '30504069', display: 'Laringoplastia por injeção' },
      { system: 'CID-10', code: 'J38.0', display: 'Paralisia das cordas vocais' },
    ],
    meshTerms: ['Laryngoplasty', 'Vocal Cord Paralysis', 'Voice Disorders', 'Injection', 'Medialization'],
    commonDiagnoses: ['J38.0'],
    avgDurationMinutes: 30,
    complexity: 2,
  },

  // ── CABEÇA E PESCOÇO ─────────────────────────────────────────────────────
  {
    id: 'parotidectomia-superficial',
    name: 'Parotidectomia Superficial',
    nameEN: 'Superficial Parotidectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30101010', display: 'Parotidectomia superficial' },
      { system: 'CID-10', code: 'D11.0', display: 'Neoplasia benigna da glândula parótida' },
    ],
    meshTerms: ['Parotidectomy', 'Parotid Gland', 'Salivary Gland Neoplasms', 'Facial Nerve', 'Pleomorphic Adenoma'],
    commonDiagnoses: ['D11.0', 'K11.6'],
    avgDurationMinutes: 120,
    complexity: 4,
  },
  {
    id: 'parotidectomia-total',
    name: 'Parotidectomia Total',
    nameEN: 'Total Parotidectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30101028', display: 'Parotidectomia total' },
      { system: 'CID-10', code: 'C07', display: 'Neoplasia maligna da glândula parótida' },
    ],
    meshTerms: ['Parotidectomy', 'Parotid Neoplasms', 'Facial Nerve', 'Mucoepidermoid Carcinoma'],
    commonDiagnoses: ['C07'],
    avgDurationMinutes: 180,
    complexity: 5,
  },
  {
    id: 'tireoidectomia-total',
    name: 'Tireoidectomia Total',
    nameEN: 'Total Thyroidectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30715011', display: 'Tireoidectomia total' },
      { system: 'CID-10', code: 'C73', display: 'Neoplasia maligna da glândula tireoide' },
    ],
    meshTerms: ['Thyroidectomy', 'Thyroid Gland', 'Thyroid Neoplasms', 'Parathyroid Glands', 'Recurrent Laryngeal Nerve'],
    guidelines: [{ title: 'ATA Management Guidelines for Thyroid Nodules and DTC', organization: 'ATA', year: 2015, url: 'https://www.liebertpub.com/doi/10.1089/thy.2015.0020' }],
    commonDiagnoses: ['C73', 'D34', 'E04'],
    avgDurationMinutes: 120,
    complexity: 4,
  },
  {
    id: 'tireoidectomia-hemi',
    name: 'Hemi-Tireoidectomia (Lobectomia)',
    nameEN: 'Hemithyroidectomy / Thyroid Lobectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30715003', display: 'Tireoidectomia parcial' },
      { system: 'CID-10', code: 'D34', display: 'Neoplasia benigna da glândula tireoide' },
    ],
    meshTerms: ['Thyroidectomy', 'Thyroid Nodule', 'Lobectomy', 'Follicular Neoplasm'],
    commonDiagnoses: ['D34', 'E04.1'],
    avgDurationMinutes: 75,
    complexity: 3,
  },
  {
    id: 'esvaziamento-cervical-seletivo',
    name: 'Esvaziamento Cervical Seletivo',
    nameEN: 'Selective Neck Dissection',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30207015', display: 'Esvaziamento cervical seletivo' },
      { system: 'CID-10', code: 'C77.0', display: 'Metástase ganglionar cervical' },
    ],
    meshTerms: ['Neck Dissection', 'Lymph Node Dissection', 'Head and Neck Neoplasms', 'Sentinel Lymph Node'],
    commonDiagnoses: ['C77.0', 'C73', 'C01'],
    avgDurationMinutes: 150,
    complexity: 4,
  },
  {
    id: 'esvaziamento-cervical-radical-modificado',
    name: 'Esvaziamento Cervical Radical Modificado',
    nameEN: 'Modified Radical Neck Dissection',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30207023', display: 'Esvaziamento cervical radical modificado' },
      { system: 'CID-10', code: 'C77.0', display: 'Metástase ganglionar cervical' },
    ],
    meshTerms: ['Neck Dissection', 'Modified Radical', 'Spinal Accessory Nerve', 'Internal Jugular Vein'],
    commonDiagnoses: ['C77.0'],
    avgDurationMinutes: 210,
    complexity: 5,
  },

  // ── PEDIÁTRICO ───────────────────────────────────────────────────────────
  {
    id: 'adenoidectomia',
    name: 'Adenoidectomia',
    nameEN: 'Adenoidectomy',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30302014', display: 'Adenoidectomia' },
      { system: 'CID-10', code: 'J35.2', display: 'Hipertrofia das adenoides' },
    ],
    meshTerms: ['Adenoidectomy', 'Adenoid Hypertrophy', 'Nasopharyngeal Tonsil', 'Obstructive Sleep Apnea'],
    commonDiagnoses: ['J35.2', 'J35.3', 'H65'],
    avgDurationMinutes: 20,
    complexity: 1,
  },
  {
    id: 'amigdalectomia',
    name: 'Amigdalectomia',
    nameEN: 'Tonsillectomy',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30302022', display: 'Amigdalectomia' },
      { system: 'CID-10', code: 'J35.1', display: 'Hipertrofia das amígdalas' },
    ],
    meshTerms: ['Tonsillectomy', 'Tonsil Diseases', 'Palatine Tonsil', 'Tonsillitis', 'Peritonsillar Abscess'],
    guidelines: [{ title: 'Tonsillectomy in Children — Update', organization: 'AAO-HNS', year: 2019, url: 'https://www.entnet.org/resource/tonsillectomy-in-children-update/' }],
    commonDiagnoses: ['J35.0', 'J35.1', 'J03'],
    avgDurationMinutes: 30,
    complexity: 1,
  },
  {
    id: 'amigdaloadenoidectomia',
    name: 'Adenoamigdalectomia (AA)',
    nameEN: 'Adenotonsillectomy',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30302030', display: 'Adenoamigdalectomia' },
      { system: 'CID-10', code: 'J35.3', display: 'Hipertrofia das amígdalas com adenoides' },
    ],
    meshTerms: ['Adenotonsillectomy', 'Obstructive Sleep Apnea', 'Pediatric', 'Upper Airway'],
    guidelines: [{ title: 'Tonsillectomy in Children — Update', organization: 'AAO-HNS', year: 2019, url: 'https://www.entnet.org/resource/tonsillectomy-in-children-update/' }],
    commonDiagnoses: ['J35.3', 'G47.3'],
    avgDurationMinutes: 35,
    complexity: 1,
  },

  // ── CIRURGIA DO SONO ─────────────────────────────────────────────────────
  {
    id: 'uvulopalatofaringoplastia',
    name: 'Uvulopalatofaringoplastia (UPFP)',
    nameEN: 'Uvulopalatopharyngoplasty (UPPP)',
    subspecialty: 'sleep-surgery',
    codes: [
      { system: 'TUSS', code: '30302057', display: 'Uvulopalatofaringoplastia' },
      { system: 'CID-10', code: 'G47.3', display: 'Apneia do sono' },
    ],
    meshTerms: ['Uvulopalatopharyngoplasty', 'Sleep Apnea Syndromes', 'Obstructive Sleep Apnea', 'UPPP'],
    guidelines: [{ title: 'Clinical Practice Guideline: Obstructive Sleep Apnea in Adults', organization: 'AAO-HNS', year: 2023, url: 'https://www.entnet.org/resource/obstructive-sleep-apnea-in-adults/' }],
    commonDiagnoses: ['G47.3'],
    avgDurationMinutes: 60,
    complexity: 3,
  },
]

