import type { ENTOntologyEntry } from '@otto/shared-types'

/** Top 30 procedimentos ENT brasileiros — seed inicial */
export const ENT_PROCEDURES_SEED: ENTOntologyEntry[] = [
  {
    id: 'timpanoplastia-tipo-1',
    name: 'Timpanoplastia Tipo I (Miringoplastia)',
    nameEN: 'Tympanoplasty Type I (Myringoplasty)',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602011', display: 'Timpanoplastia tipo I' },
      { system: 'CID-10', code: 'H72', display: 'Perfuração da membrana do tímpano' },
    ],
    meshTerms: ['Tympanoplasty', 'Myringoplasty', 'Tympanic Membrane Perforation'],
    guidelines: [{ title: 'AAO-HNS Tympanoplasty Guidelines', organization: 'AAO-HNS', year: 2019, url: 'https://www.entnet.org' }],
    commonDiagnoses: ['H72', 'H66'],
    avgDurationMinutes: 90,
    complexity: 2,
  },
  {
    id: 'estapedotomia',
    name: 'Estapedotomia / Estapedectomia',
    nameEN: 'Stapedotomy / Stapedectomy',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602038', display: 'Estapedotomia' },
      { system: 'CID-10', code: 'H80', display: 'Otosclerose' },
    ],
    meshTerms: ['Stapedectomy', 'Stapedotomy', 'Otosclerosis', 'Stapes Surgery'],
    commonDiagnoses: ['H80'],
    avgDurationMinutes: 75,
    complexity: 4,
  },
  {
    id: 'mastoidectomia',
    name: 'Mastoidectomia',
    nameEN: 'Mastoidectomy',
    subspecialty: 'otology',
    codes: [
      { system: 'TUSS', code: '30602089', display: 'Mastoidectomia' },
      { system: 'CID-10', code: 'H70', display: 'Mastoidite e afecções relacionadas' },
    ],
    meshTerms: ['Mastoidectomy', 'Mastoiditis', 'Cholesteatoma'],
    commonDiagnoses: ['H70', 'H71'],
    avgDurationMinutes: 120,
    complexity: 3,
  },
  {
    id: 'septoplastia',
    name: 'Septoplastia',
    nameEN: 'Septoplasty',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401018', display: 'Septoplastia' },
      { system: 'CID-10', code: 'J34.2', display: 'Desvio do septo nasal' },
    ],
    meshTerms: ['Septoplasty', 'Nasal Septum Deviation', 'Nasal Obstruction'],
    commonDiagnoses: ['J34.2'],
    avgDurationMinutes: 60,
    complexity: 2,
  },
  {
    id: 'fess',
    name: 'Cirurgia Endoscópica Sinusal Funcional (FESS)',
    nameEN: 'Functional Endoscopic Sinus Surgery (FESS)',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401050', display: 'Cirurgia endoscópica do seio paranasal' },
      { system: 'CID-10', code: 'J32', display: 'Sinusite crônica' },
    ],
    meshTerms: ['Endoscopy', 'Sinusitis', 'Paranasal Sinuses', 'Functional Endoscopic Sinus Surgery'],
    guidelines: [{ title: 'EPOS 2020', organization: 'European Position Paper on Rhinosinusitis', year: 2020, url: 'https://www.rhinologyjournal.com/EPOS2020' }],
    commonDiagnoses: ['J32', 'J33'],
    avgDurationMinutes: 90,
    complexity: 3,
  },
  {
    id: 'turbinectomia',
    name: 'Turbinoplastia / Turbinectomia',
    nameEN: 'Turbinoplasty / Turbinectomy',
    subspecialty: 'rhinology',
    codes: [
      { system: 'TUSS', code: '30401034', display: 'Turbinectomia' },
      { system: 'CID-10', code: 'J34.3', display: 'Hipertrofia dos cornetos nasais' },
    ],
    meshTerms: ['Turbinectomy', 'Nasal Turbinates', 'Inferior Turbinate Reduction'],
    commonDiagnoses: ['J34.3', 'J30'],
    avgDurationMinutes: 30,
    complexity: 1,
  },
  {
    id: 'adenoidectomia',
    name: 'Adenoidectomia',
    nameEN: 'Adenoidectomy',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30302014', display: 'Adenoidectomia' },
      { system: 'CID-10', code: 'J35.2', display: 'Hipertrofia das adenoides' },
    ],
    meshTerms: ['Adenoidectomy', 'Adenoid Hypertrophy', 'Nasopharyngeal Tonsil'],
    commonDiagnoses: ['J35.2', 'J35.3', 'H65'],
    avgDurationMinutes: 20,
    complexity: 1,
  },
  {
    id: 'amigdalectomia',
    name: 'Amigdalectomia',
    nameEN: 'Tonsillectomy',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30302022', display: 'Amigdalectomia' },
      { system: 'CID-10', code: 'J35.1', display: 'Hipertrofia das amígdalas' },
    ],
    meshTerms: ['Tonsillectomy', 'Tonsil Diseases', 'Palatine Tonsil', 'Tonsillitis'],
    commonDiagnoses: ['J35.0', 'J35.1', 'J03'],
    avgDurationMinutes: 30,
    complexity: 1,
  },
  {
    id: 'traqueostomia',
    name: 'Traqueostomia',
    nameEN: 'Tracheostomy',
    subspecialty: 'laryngology',
    codes: [
      { system: 'TUSS', code: '30504050', display: 'Traqueostomia' },
      { system: 'CID-10', code: 'J04', display: 'Laringite e traqueíte agudas' },
    ],
    meshTerms: ['Tracheostomy', 'Airway Management', 'Trachea'],
    commonDiagnoses: ['J04', 'J38.6', 'Q31'],
    avgDurationMinutes: 45,
    complexity: 3,
  },
  {
    id: 'microcirurgia-laringe',
    name: 'Microcirurgia de Laringe',
    nameEN: 'Laryngeal Microsurgery',
    subspecialty: 'laryngology',
    codes: [
      { system: 'TUSS', code: '30504034', display: 'Microcirurgia de laringe' },
      { system: 'CID-10', code: 'J38.1', display: 'Pólipo de corda vocal e laringe' },
    ],
    meshTerms: ['Laryngoscopy', 'Vocal Cord', 'Laryngeal Diseases', 'Phonosurgery'],
    commonDiagnoses: ['J38.0', 'J38.1', 'J38.2'],
    avgDurationMinutes: 60,
    complexity: 3,
  },
  {
    id: 'parotidectomia',
    name: 'Parotidectomia',
    nameEN: 'Parotidectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30101010', display: 'Parotidectomia total ou parcial' },
      { system: 'CID-10', code: 'D11', display: 'Neoplasia benigna das glândulas salivares maiores' },
    ],
    meshTerms: ['Parotidectomy', 'Parotid Gland', 'Salivary Gland Neoplasms', 'Facial Nerve'],
    commonDiagnoses: ['D11.0', 'C07', 'K11.6'],
    avgDurationMinutes: 150,
    complexity: 5,
  },
  {
    id: 'tireoidectomia-total',
    name: 'Tireoidectomia Total',
    nameEN: 'Total Thyroidectomy',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30715011', display: 'Tireoidectomia total' },
      { system: 'CID-10', code: 'C73', display: 'Neoplasia maligna da glândula tireoide' },
    ],
    meshTerms: ['Thyroidectomy', 'Thyroid Gland', 'Thyroid Neoplasms', 'Parathyroid Glands'],
    commonDiagnoses: ['C73', 'D34', 'E04'],
    avgDurationMinutes: 120,
    complexity: 4,
  },
  {
    id: 'esvaziamento-cervical',
    name: 'Esvaziamento Cervical',
    nameEN: 'Neck Dissection',
    subspecialty: 'head-neck',
    codes: [
      { system: 'TUSS', code: '30207015', display: 'Esvaziamento cervical radical modificado' },
      { system: 'CID-10', code: 'C77.0', display: 'Neoplasia maligna dos gânglios linfáticos da cabeça, face e pescoço' },
    ],
    meshTerms: ['Neck Dissection', 'Lymph Node Dissection', 'Head and Neck Neoplasms'],
    commonDiagnoses: ['C77.0', 'C73', 'C01'],
    avgDurationMinutes: 180,
    complexity: 5,
  },
  {
    id: 'ventilacao-transtimpanica',
    name: 'Inserção de Tubo de Ventilação Transtimpânico (TVT)',
    nameEN: 'Tympanostomy Tube Insertion',
    subspecialty: 'pediatric-ent',
    codes: [
      { system: 'TUSS', code: '30602046', display: 'Miringotomia com tubo de ventilação' },
      { system: 'CID-10', code: 'H65', display: 'Otite média não supurativa' },
    ],
    meshTerms: ['Middle Ear Ventilation', 'Tympanostomy', 'Otitis Media with Effusion', 'Grommets'],
    commonDiagnoses: ['H65.0', 'H65.2', 'H65.3'],
    avgDurationMinutes: 15,
    complexity: 1,
  },
]
